# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-01 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=1)),
            ],
        ),
    ]
