# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-12 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mood',
            old_name='status',
            new_name='name',
        ),
    ]
