# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20180118_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nickname',
            field=models.CharField(max_length=20, verbose_name=b'\xe6\x91\x98\xe8\xa6\x81'),
        ),
    ]
