# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_auto_20180118_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nickname',
        ),
    ]
