# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_remove_product_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nickname',
            field=models.CharField(default=b'\xe8\xb6\x85\xe5\x80\xbc\xe4\xba\x8c\xe6\x89\x8b\xe6\x9c\xba', max_length=20, verbose_name=b'\xe6\x91\x98\xe8\xa6\x81'),
        ),
    ]
